[package]
name = "icp_scholar_core_backend_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
[dependencies]
candid = "0.10.14"       # ✅ just the version, no features
ic-cdk = "0.12.3"
ic-cdk-macros = "0.8"
serde = { version = "1", features = ["derive"] }

